version: '3'

services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}
  
  products-microservice:
    build: ./products-ms
    ports:
      - "3001:3001"
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=${NATS_SERVERS}
  
  orders-microservice:
    depends_on:
      - orders-db
      - nats-server
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}

  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
  
  payments-microservice:
    container_name: payments-ms
    build: ./payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:3003
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}