version: '3'

services:

  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}
  
  products-microservice:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=${NATS_SERVERS}
  
  orders-microservice:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        ORDER_DATABASE_URL: ${ORDER_DATABASE_URL}
    image: orders-ms-prod
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDER_DATABASE_URL}
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}

  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb
  
  payments-microservice:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  auth-microservice:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=3004
      - NATS_SERVICE_NAME=${NATS_SERVICE_NAME}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}